on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Doxygen
        shell: bash
        run: doxygen
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.3
  
